django_capstone/blog/urls.py
from django.views.generic import ListView, DetailView
from django.urls import path
from.models import Post

app_name = 'blog'

urlpatterns = [
    path('', ListView.as_view(queryset=Post.objects.all().order_by("-date")[:25], template_name="blog.html")),
    path('<int:pk>/', DetailView.as_view(model=Post, template_name="post.html")),

]

django_capstone/django_capstone/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include("malema.urls")),
    path('', include('users.urls')),
    path('', include('django.contrib.auth.urls')),

]

django_capstone/malema/urls.py
from django.urls import path
from . import views

app_name = 'malema'

urlpatterns = [
    path('biography/', views.biography, name='biography'),
    path('life_and_education/', views.life_and_education, name='life_and_education'),
    path('anc_youth/', views.anc_youth, name='anc_youth'),

]

django_capstone/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name= 'users'

urlpatterns =[

    path("register/", views.register_request, name="register"),
    path('', views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path('home/', views.home, name='home'),

]

django_capstone/blog/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    """
    A class to represent a post
    ...
    Atrributes
    ----------
    id : int
    title : str
    body :
    date :
    signature : 
    """
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField()
    signature = models.CharField(max_length=200)

def __str__(self):
    return self.title

django_capstone/malema/models.py
from django.db import models

# Create your models here.

django_capstone/users/models.py
from django.db import models

# Create your models here.

django_capstone/malema/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

django_capstone/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

django_capstone/blog/views.py
from django.shortcuts import render

# Create your views here.

django_capstone/malema/views.py
from django.http import HttpResponse
from django.shortcuts import render



# Create your views here.

def biography(request):
    """displays biography page"""
    return render(request, 'biography.html')

def life_and_education(request):
    return render(request, 'life_and_education.html')

def anc_youth(request):
    return render(request, 'anc_youth.html')

django_capstone/users/views.py
from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required


def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("main:homepage")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="users/register.html", context={"register_form":form})


def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("users:home")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="users/login.html", context={"login_form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return redirect("users:login")

@login_required(login_url='/logout/')
def home(request):
    return render(request, 'users/home.html')

django_capstone/blog/templates/blog.html
<h1>Blog posts</h1>

{% block content %}
{% for post in object_list %}
<h5>
{{post.date|date:"Y-m-d"}}
<a href = "/blog/{{ post.id }}"> {{post.title}}</a>
</h5>
{% endfor %}
{% endblock %}

django_capstone/blog/templates/post.html
{% block content %}
<h3>
    <a href ="/blog/{{ post.id }}"> {{ post.title }} </a>
</h3>

<div class="container">
    {{post.body|safe| linebreaks }}
    {{post.signature|safe|linebreaks}}
</div>
<br><br>
{% endblock %}

django_capstone/malema/templates/anc_youth.html
<!DOCTYPE html>
<head>
    <title>ANC YOUTH</title>


</head>

<body>
<P>
<center>
  <h3><b>Election as president: April 2008</b></h3>
  By 2008, Malema was the provincial secretary of the Limpopo branch of the ANC Youth League and a leading contender for election as president of the national league. His candidacy had the support of outgoing league president Fikile Mbalula, while outgoing league secretary-general Sihle Zikalala supported the more moderate candidate, Saki Mofokeng.
  Following an extremely heated campaign and a disorderly plenary, Malema was elected ANC Youth League president at the league's 23rd National Conference in Bloemfontein in April 2008. He received 1,833 votes against Mofokeng's 1,696 votes and was elected alongside a slate of allies, including Andile Lungisa as deputy president.<p>
  The outcome of the vote was immediately disputed, including by conference delegates who claimed that incidents of intimidation had prevented them from voting. The conference devolved into disorder, with some delegates throwing chairs, and adjourned without concluding its business.
  Malema later criticised the "unbecoming conduct" shown by delegates at the conference. Following an intervention by the mainstream ANC, the league held a special closed congress in Johannesburg in June. On the recommendation of Gwede Mantashe, the secretary-general of the mainstream ANC, Mofokeng agreed to affirm the results of the election held in April.<p>
  <h3><b>Support for Zuma: 2008–2010</b></h3>
By the time of his election as Youth League president, Malema, like most of the league's membership, was a strong supporter of ANC president Jacob Zuma and an outspoken critic of former ANC president Thabo Mbeki.
  In June 2008, he defended Zuma – then facing prosecution on corruption charges – at a rally in Thaba 'Nchu, Free State, famously (and to broad condemnation) announcing, "We are prepared to die for Zuma... We are prepared to take up arms and kill for Zuma".<p>
  In September, he vowed to "eliminate any force" that sought to block Zuma from the national presidency.
  Ahead of the 2009 general election, Malema was nominated to stand for election as a Member of Parliament but declined on the grounds that Parliament was "for old people". Nonetheless, he campaigned energetically for the ANC and for Zuma, the party's presidential candidate, in the election.
  In April 2009, for example, he and the rest of a league delegation were asked to leave Port Elizabeth's Dora Nginza Hospital, where they had been canvassing support in the wards.<p>
  After the election, Malema launched a programme of school visits in an apparent attempt to reach the country's youth.
  Kgalema Motlanthe, then the ANC deputy president and Deputy President of South Africa, criticised the visits as disruptive to the students' education.
  Although Malema remained an ally of Zuma in the months after his election as President of South Africa in May 2009, they fell out publicly by mid-2010.
  Malema later explained that he had turned on Zuma when he realised Zuma was incapable of fulfilling the left-wing policy agenda that had secured his election as ANC president in 2007; according to Malema, Zuma took a harsher stance towards the league only after it rejected him.
  According to an alternative interpretation, however, Zuma adjusted his stance towards Malema and the league in 2010 – notably by instituting disciplinary proceedings against Malema – because he realised that Malema's outspoken militancy constituted a political liability for him or a political threat to him.
</center>

</p>

</body>
</html>

django_capstone/malema/templates/biography.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>

<style>
h1 {
  text-align: center;
}
</style>

    <title>julius malema biography</title>
     <link rel="stylesheet" type="text/css">


</head>
<body>
    <center>
<p><h3>Julius Sello Malema</h3><p>
         Born on 3 March 1981, Malema was born and raised in the township of Seshego near Polokwane in the Transvaal, in the region now known as Limpopo.
    His family is Northern Sotho , and his mother was a domestic worker and a single parent. After his mother died, he was raised by his grandmother, who died in May 2019.<p>

    (born 3 March 1981) is a South African politician who is a Member of Parliament and the leader of the Economic Freedom Fighters (EFF), a left-wing party which he founded in 2013.
    He was formerly the President of the African National Congress (ANC) Youth League from 2008 until his expulsion from the party in 2012.
    Malema became a member of the ANC at the age of nine and was elected president of the ANC Youth League at a controversial party conference in April 2008.
    He rose to prominence as an outspoken supporter of <B>Jacob Zuma</b>, then the ANC president and later the President of South Africa.<p>
    However, Malema's relationship with Zuma grew strained after Malema was sanctioned by the ANC for various disciplinary infractions in May 2010; he campaigned for Zuma to be removed from office ahead of the ANC's 53rd National Conference.
    Months before that conference, in April 2012, Malema was expelled from the ANC for bringing the party into disrepute.
    While ANC Youth League president, he was an early proponent of proposals to nationalise South Africa's mining industry and expropriate land without compensation, policy positions that the EFF inherited.
    As the founding president and "commander-in-chief" of the EFF, Malema was elected to a seat in the National Assembly in 2014. He was re-elected to a second five-year parliamentary term in 2019.
    Malema was described by both Zuma and the Premier of Limpopo Province, Cassel Mathale, as the "future leader" of South Africa.<p>
    Less favourable portraits paint him as a "reckless populist" with the potential to destabilise South Africa and to spark racial conflict.
    He has been convicted of hate speech twice: once in March 2010 for demeaning comments about Zuma's rape accuser and once in September 2011 for singing<b> "Dubul' ibhunu" ("Shoot the Boer")</b>.
    In 2012, Malema was charged with fraud, money-laundering and racketeering.
    After numerous postponements, the case was dismissed by the courts in 2015 due to excessive delays by the National Prosecuting Authority, leading to perceptions that the charges were politically motivated.
    However, AfriForum announced in 2018 that it would mount a private prosecution of Malema on the corruption charges.
</center>

 next page:
    <a href="{% url 'malema:life_and_education' %}">life and education</a>


</body>
</html>

django_capstone/malema/templates/life_and_education.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Early life and education</title>

</head>
<body>


<center>
    <h3><b>Student politics</b></h3>
    According to Malema, he joined the Masupatsela ("trailblazers") movement of the African National Congress (ANC) at the age of nine or ten.
    His main task at the time was to remove National Party posters. In 1995, Malema joined the ANC Youth League and became the chairperson of his local branch in Seshego and of the regional branch in broader Capricorn.
    In 1997, he became the provincial chairperson of the Congress of South African Students (COSAS) in Limpopo.
    He was elected as national president of COSAS in 2001. In May of the following year, he led a COSAS students' march through Johannesburg; the march was marked by incidents of violence and looting.<p>
    <h3><b>Education</b></h3>
    Malema matriculated from Mohlakaneng High School in Seshego. In 2010, he completed a two-year diploma in youth development through the University of South Africa (UNISA).
    Also at UNISA, he subsequently completed a Bachelor of Arts in communications and African languages in March 2016 an Honours degree in philosophy in 2017.
    In 2018, he enrolled in a Master's degree programme at the University of the Witwatersrand.<p>

</center>
next page:
    <a href="{% url 'malema:anc_youth' %}">anc youth</a>


</body>
</html>

django_capstone/users/templates/users/home.html
<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Home Page</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css">

    <style>

body {
    background-image:url('https://media.citizen.co.za/wp-content/uploads/2023/05/Julius-Malema-US-Souh-Africa-Russia-1536x1024.jpg');
    background-repeat: no-repeat;
    background-size: cover;
}
h1{

    color: white;
    size: 100cm;
    font-weight: bold;
    font-size: 50px;


}
h3{
    color:#080707;
    font-family:cursive ;
    text-align: center;
}
h2{
color: #080707;
font-family:cursive;
}
h4{
color: #080707;
font-family:cursive;
}

a{
    color: white;
    size: 100cm;
    font-weight: bold;
}
p{
    text-align: center;
}

.bottom-text {
    position: absolute;
    bottom: 0;
    color: white;
    size: 100cm;
    font-weight: bold;
    font-size: 40px;

}
  .container {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem;


  }
  nav ul {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;

  }
  nav li {
    margin: 0 1rem;
  }
  nav a {
    text-decoration: none;
    color: white;

  }
  nav a:hover {
    color: black;
  }


    </style>
<body>
    <header>
        <div class="container">
            <h1>Julius Malema</h1><br>
            <nav>
                <ul>
                    <li><a href="{% url 'malema:biography' %}">Biography</a></li>
                    <li><a href="http://127.0.0.1:8000/blog/">Blog</a> </li>
                    <li><a href="{% url 'users:login' %}">logout</a></li>





                </ul>
            </nav>
        </div>
    </header>

    <div class="container">
        <div class="bottom-text">
        “We are heading to darkness”
                           <p>—Julius Malema</p>
        </div>
    </div>
    </body>
</html>

django_capstone/users/templates/users/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Login Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>

      form {
        background-color: #f5f5f5;
        border-radius: 10px;
        padding: 30px;
        margin-top: 50px;
      }

      label {
        font-weight: bold;
      }

      input[type="text"], input[type="password"] {
        border-radius: 5px;
        padding: 8px;
        border: none;
        box-shadow: none;
        border: 1px solid #ccc;
      }

      input[type="submit"] {
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 8px 20px;
        font-weight: bold;
      }

      input[type="submit"]:hover {
        background-color: #0062cc;
        cursor: pointer;
      }

      a {
        color: #007bff;
      }
      p{
      border-radius: 5px;
        padding: 8px;
        border: none;
        box-shadow: none;
        border: 1px solid #ccc;

      }
    </style>
  {% block content %}


<!--Login-->
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form}}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>

{% endblock %}

django_capstone/users/templates/users/logout.html
{% block content %}
    <br>
    <div class="alert alert-success" role="alert">
        <h2 style="text-align: center;">Logged out!</h2>
    </div>

    <h3>Login again?</h3>
    <a href="{% url 'users:login' %}">---> Login</a> <br>

{% endblock content %}

django_capstone/users/templates/users/register.html
<!DOCTYPE html>
<html>
  <head>
    <title>Login Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
      form {
  margin: 0 auto;
  width: 50%;
}

label {
  font-weight: bold;
}

.invalid-feedback {
  display: none;
  color: red;
  margin-top: 5px;
}

input:invalid + .invalid-feedback {
  display: block;
}

input:focus {
  border-color: #80bdff;
  box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
}

button[type="submit"] {
  margin-top: 10px;
}
p{
      border-radius: 5px;
        padding: 8px;
        border: none;
        box-shadow: none;
        border: 1px solid #ccc;

      }
</style>
 {% block content %}
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form }}

		<button class="btn btn-primary" type="submit">Register</button>
	</form>

</div>

{% endblock %}